### PR TITLE
Enable CAS Proxy mechanism and store PGT to AccessToken

### PR DESCRIPTION
**Pull request by Omicron7**

### CODE REVIEW

**Comment by twinge** [comment]
Do we have a test suite for this app?

**Comment by Omicron7** [comment]
no, got any good docs on implementing one?

**Comment by twinge** [comment]
Mostly by example: https://github.com/CruGlobal/mpdx/tree/master/spec

https://github.com/rspec/rspec-rails

**Comment by twinge** [comment]
Mark might have a book on his shelf

**Comment by twinge** [comment]
:+1:

**Pull request merged**
